language: java
script: mvn clean install
deploy:
  provider: s3
  access_key_id: AKIAIED7VDGKPQL4CCHA
  secret_access_key:
    secure: kBKq4f/qRFmCg1uoHn6thMDW55+uUuHxZd0+bYgouHgnP8apDyoYFFDZOS+rUROtin/+207BFiyQ3K0HSmq+BmQc/UxRReDa6bB96LYw2v+umbAJo1SWqqo4LkdYgnPJ5LFgLwVZiTpIHzUNBNsvT1T/5WZJvd8+2S5YfwUxym8=
  bucket: maciek-ban-proj
  on:
    repo: siwydb/psoirWorker
